name: Docker
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  IMAGE_NAME: liuzhen932/app-icecast

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: liuzhen932
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ env.IMAGE_NAME }}
          tags: |
            latest

      - name: Get Current Date
        id: date
        run: echo "date=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            DATE_CREATED=${{ steps.date.outputs.date }}
          tags: ${{ steps.meta.outputs.tags }}
